mode:

interop_threads: 4
intraop_threads: 1

data:
  swda_path: 'deps/swda/swda'
  text_path: 'deps/transformers/examples/ner'
  dialog_acts_per_window: 50
  dialog_acts_overlap: 3

model:
  path: '/home/pzelasko/daseg/deps/transformers/examples/ner/xlnet-t46-textnorm'
#  cache_dir: ""
#  tokenizer_name: ""
#  model_type: "xlnet"
#  model_name_or_path: "xlnet-base-cased"
#  seed: 42
#  use_gpu: true
#
#  save_steps: 500
#  max_steps: -1
#  num_train_epochs: 3
#
#  warmup_steps: 0
#  max_grad_norm: 1
#  adam_epsilon: 1e-8
#  weight_decay: 0
#  learning_rate: 5e-5
#  gradient_accumulation_steps: 1
#
#  per_gpu_eval_batch_size: 8
#  per_gpu_train_batch_size: 8
#
#  do_lower_case: false
#
#  evaluate_during_training: true
#
#  max_seq_length: 512
